### ISSUE TITLE
Being alerted of using legacy editor when it's disabled

### ISSUE THREAD

**Issue by andrezgz** [joethei/obsidian-control-characters#1]
I triple checked that the option "Use legacy editor" is disabled. Even though, when I try to enable this plugin I receive the following notice:
> Control Characters: You are using the legacy editor, this plugin is not supported there

**Comment by joethei** [comment]
oops, got a condition the wrong way,
will be fixed in the next update(later today)

**Comment by andrezgz** [comment]
Thanks! It's working :)
