### ISSUE TITLE
Question: How to change the color of the marks?

### ISSUE THREAD

**Issue by Liong1976** [joethei/obsidian-control-characters#5]
First of all, I want to say thank you for making this plugin for I used to rely on the Show Whitespace plugin which is not compatible with the new editor anymore.

Is there any way to change the color of the characters (marks) by using a CSS snippet so that they stand out to me?

**Comment by Liong1976** [comment]
Thanks, @joethei, I do appreciate it!

**Comment by Liong1976** [comment]
I had installed the newest version of your plugin. However, I couldn't locate the new feature in the Style Setting plugin.
![image](https://user-images.githubusercontent.com/88898230/162070866-b80df2a9-b9c4-456e-8dec-0a1eee38ed0a.png)

**Comment by joethei** [comment]
Whoops, seems like the style settings support did not ship properly.
(Comments were removed automatically, which is what style settings uses.)

**Comment by Liong1976** [comment]
Thanks, @joethei!
